"""
Catalog Data for Structon
Contains categories, subcategories, and locale-specific labels.
"""

CATEGORIES = {
    'graafbakken': {
        'title': 'Graafbakken',
        'title_translations': {
            'be-nl': 'Graafbakken', 'nl-nl': 'Graafbakken',
            'be-fr': 'Godets de terrassement', 'de-de': 'Baggerschaufeln'
        },
        'description': 'Professionele graafbakken voor alle grondwerkzaamheden. Van standaard graafwerk tot gespecialiseerde toepassingen zoals drainage, rioleringen en funderingen.',
        'description_translations': {
            'be-nl': 'Professionele graafbakken voor alle grondwerkzaamheden. Van standaard graafwerk tot gespecialiseerde toepassingen zoals drainage, rioleringen en funderingen.',
            'nl-nl': 'Professionele graafbakken voor alle grondwerkzaamheden. Van standaard graafwerk tot gespecialiseerde toepassingen zoals drainage, rioleringen en funderingen.',
            'be-fr': 'Godets de terrassement professionnels pour tous les travaux de terrassement.',
            'de-de': 'Professionelle Baggerschaufeln für alle Erdarbeiten.'
        },
        'subcategories': ['slotenbakken', 'dieplepelbakken', 'sleuvenbakken', 'kantelbakken', 'rioolbakken', 'trapezium-bakken']
    },
    'sloop-sorteergrijpers': {
        'title': 'Sloop- & Sorteergrijpers',
        'title_translations': {
            'be-nl': 'Sloop- & Sorteergrijpers', 'nl-nl': 'Sloop- & Sorteergrijpers',
            'be-fr': 'Pinces de démolition et de tri', 'de-de': 'Abbruch- & Sortiergreifer'
        },
        'description': 'Robuuste sloop- en sorteergrijpers voor afbraak, recycling en materiaalverwerking.',
        'description_translations': {
            'be-nl': 'Robuuste sloop- en sorteergrijpers voor afbraak, recycling en materiaalverwerking.',
            'nl-nl': 'Robuuste sloop- en sorteergrijpers voor afbraak, recycling en materiaalverwerking.',
            'be-fr': 'Pinces de démolition et de tri robustes pour la démolition et le recyclage.',
            'de-de': 'Robuste Abbruch- und Sortiergreifer für Abriss und Recycling.'
        },
        'subcategories': ['sorteergrijpers', 'sloopgrijpers', 'puingrijpers']
    },
    'overige': {
        'title': 'Overige Aanbouwdelen',
        'title_translations': {
            'be-nl': 'Overige Aanbouwdelen', 'nl-nl': 'Overige Aanbouwdelen',
            'be-fr': 'Autres accessoires', 'de-de': 'Sonstige Anbaugeräte'
        },
        'description': 'Gespecialiseerde aanbouwdelen voor specifieke toepassingen.',
        'description_translations': {
            'be-nl': 'Gespecialiseerde aanbouwdelen voor specifieke toepassingen.',
            'nl-nl': 'Gespecialiseerde aanbouwdelen voor specifieke toepassingen.',
            'be-fr': 'Accessoires spécialisés pour des applications spécifiques.',
            'de-de': 'Spezialisierte Anbaugeräte für spezifische Anwendungen.'
        },
        'subcategories': ['ripper-tanden', 'hydraulische-hamers', 'egaliseerbalken', 'verdichtingsplaten']
    }
}

SUBCATEGORIES = {
    'slotenbakken': {
        'title': 'Slotenbakken', 'parent_category': 'graafbakken',
        'title_translations': {'be-nl': 'Slotenbakken', 'nl-nl': 'Slotenbakken', 'be-fr': 'Godets à tranchées', 'de-de': 'Grabenschaufeln'},
        'description': 'Slotenbakken zijn gespecialiseerde smalle graafbakken voor het graven van sleuven en leidingsloten.',
        'description_translations': {'be-nl': 'Slotenbakken zijn gespecialiseerde smalle graafbakken voor het graven van sleuven en leidingsloten.', 'nl-nl': 'Slotenbakken zijn gespecialiseerde smalle graafbakken voor het graven van sleuven en leidingsloten.', 'be-fr': 'Les godets à tranchées sont des godets étroits spécialisés.', 'de-de': 'Grabenschaufeln sind spezialisierte schmale Schaufeln.'},
        'long_description': 'Slotenbakken zijn gespecialiseerde smalle graafbakken ontworpen voor het graven van sleuven en leidingsloten. Met hun smalle breedte en geoptimaliseerde vorm zijn ze ideaal voor het aanleggen van kabels, leidingen en drainage. De robuuste constructie uit Hardox staal garandeert een lange levensduur, zelfs bij intensief gebruik in zware grondsoorten. Verkrijgbaar in diverse breedtes vanaf 200mm voor precisiewerk.',
        'long_description_translations': {'be-nl': 'Slotenbakken zijn gespecialiseerde smalle graafbakken ontworpen voor het graven van sleuven en leidingsloten. Met hun smalle breedte en geoptimaliseerde vorm zijn ze ideaal voor het aanleggen van kabels, leidingen en drainage. De robuuste constructie uit Hardox staal garandeert een lange levensduur, zelfs bij intensief gebruik in zware grondsoorten. Verkrijgbaar in diverse breedtes vanaf 200mm voor precisiewerk.', 'nl-nl': 'Slotenbakken zijn gespecialiseerde smalle graafbakken ontworpen voor het graven van sleuven en leidingsloten. Met hun smalle breedte en geoptimaliseerde vorm zijn ze ideaal voor het aanleggen van kabels, leidingen en drainage. De robuuste constructie uit Hardox staal garandeert een lange levensduur, zelfs bij intensief gebruik in zware grondsoorten. Verkrijgbaar in diverse breedtes vanaf 200mm voor precisiewerk.', 'be-fr': 'Les godets à tranchées sont des godets étroits spécialisés conçus pour creuser des tranchées et des fossés de canalisations.', 'de-de': 'Grabenschaufeln sind spezialisierte schmale Schaufeln für das Graben von Gräben und Leitungsgräben.'}
    },
    'dieplepelbakken': {
        'title': 'Dieplepelbakken', 'parent_category': 'graafbakken',
        'title_translations': {'be-nl': 'Dieplepelbakken', 'nl-nl': 'Dieplepelbakken', 'be-fr': 'Godets profonds', 'de-de': 'Tiefschaufeln'},
        'description': 'Dieplepelbakken zijn extra diepe graafbakken voor vijvers, watergangen en diepe funderingen.',
        'description_translations': {'be-nl': 'Dieplepelbakken zijn extra diepe graafbakken voor vijvers, watergangen en diepe funderingen.', 'nl-nl': 'Dieplepelbakken zijn extra diepe graafbakken voor vijvers, watergangen en diepe funderingen.', 'be-fr': 'Les godets profonds sont des godets extra-profonds.', 'de-de': 'Tiefschaufeln sind extra tiefe Schaufeln.'},
        'long_description': 'Dieplepelbakken zijn extra diepe graafbakken voor het uitgraven van vijvers, watergangen en diepe funderingen. De verlengde constructie biedt een groter bereik en volume dan standaard graafbakken. Ideaal voor baggerwerk, vijveraanleg en situaties waar u dieper moet graven dan de standaard graafdiepte van uw machine toelaat. Vervaardigd uit hoogwaardig Hardox staal voor maximale sterkte en duurzaamheid.',
        'long_description_translations': {'be-nl': 'Dieplepelbakken zijn extra diepe graafbakken voor het uitgraven van vijvers, watergangen en diepe funderingen. De verlengde constructie biedt een groter bereik en volume dan standaard graafbakken. Ideaal voor baggerwerk, vijveraanleg en situaties waar u dieper moet graven dan de standaard graafdiepte van uw machine toelaat. Vervaardigd uit hoogwaardig Hardox staal voor maximale sterkte en duurzaamheid.', 'nl-nl': 'Dieplepelbakken zijn extra diepe graafbakken voor het uitgraven van vijvers, watergangen en diepe funderingen. De verlengde constructie biedt een groter bereik en volume dan standaard graafbakken. Ideaal voor baggerwerk, vijveraanleg en situaties waar u dieper moet graven dan de standaard graafdiepte van uw machine toelaat. Vervaardigd uit hoogwaardig Hardox staal voor maximale sterkte en duurzaamheid.', 'be-fr': 'Les godets profonds sont des godets extra-profonds pour creuser des étangs, des cours d\'eau et des fondations profondes.', 'de-de': 'Tiefschaufeln sind extra tiefe Schaufeln zum Ausheben von Teichen, Wasserläufen und tiefen Fundamenten.'}
    },
    'sleuvenbakken': {
        'title': 'Sleuvenbakken', 'parent_category': 'graafbakken',
        'title_translations': {'be-nl': 'Sleuvenbakken', 'nl-nl': 'Sleuvenbakken', 'be-fr': 'Godets à fentes', 'de-de': 'Schlitzschaufeln'},
        'description': 'Sleuvenbakken combineren smalle breedte met extra diepte voor diepe, smalle sleuven.',
        'description_translations': {'be-nl': 'Sleuvenbakken combineren smalle breedte met extra diepte voor diepe, smalle sleuven.', 'nl-nl': 'Sleuvenbakken combineren smalle breedte met extra diepte voor diepe, smalle sleuven.', 'be-fr': 'Les godets à fentes combinent une largeur étroite avec une profondeur supplémentaire.', 'de-de': 'Schlitzschaufeln kombinieren schmale Breite mit zusätzlicher Tiefe.'},
        'long_description': 'Sleuvenbakken combineren smalle breedte met extra diepte voor het graven van diepe, smalle sleuven. Perfect voor kabeltracés, drainage-installaties en leidingwerk waar precisie en diepte cruciaal zijn. De geoptimaliseerde vorm zorgt voor minimale grondverzet en een nette sleufwand. Geschikt voor alle grondsoorten en verkrijgbaar in breedtes van 200mm tot 600mm.',
        'long_description_translations': {'be-nl': 'Sleuvenbakken combineren smalle breedte met extra diepte voor het graven van diepe, smalle sleuven. Perfect voor kabeltracés, drainage-installaties en leidingwerk waar precisie en diepte cruciaal zijn. De geoptimaliseerde vorm zorgt voor minimale grondverzet en een nette sleufwand. Geschikt voor alle grondsoorten en verkrijgbaar in breedtes van 200mm tot 600mm.', 'nl-nl': 'Sleuvenbakken combineren smalle breedte met extra diepte voor het graven van diepe, smalle sleuven. Perfect voor kabeltracés, drainage-installaties en leidingwerk waar precisie en diepte cruciaal zijn. De geoptimaliseerde vorm zorgt voor minimale grondverzet en een nette sleufwand. Geschikt voor alle grondsoorten en verkrijgbaar in breedtes van 200mm tot 600mm.', 'be-fr': 'Les godets à fentes combinent une largeur étroite avec une profondeur supplémentaire pour creuser des tranchées profondes et étroites.', 'de-de': 'Schlitzschaufeln kombinieren schmale Breite mit zusätzlicher Tiefe für tiefe, schmale Gräben.'}
    },
    'kantelbakken': {
        'title': 'Kantelbakken', 'parent_category': 'graafbakken',
        'title_translations': {'be-nl': 'Kantelbakken', 'nl-nl': 'Kantelbakken', 'be-fr': 'Godets basculants', 'de-de': 'Schwenkschaufeln'},
        'description': 'Kantelbakken met hydraulisch kantelbare bak voor taluds en moeilijk bereikbare hoeken.',
        'description_translations': {'be-nl': 'Kantelbakken met hydraulisch kantelbare bak voor taluds en moeilijk bereikbare hoeken.', 'nl-nl': 'Kantelbakken met hydraulisch kantelbare bak voor taluds en moeilijk bereikbare hoeken.', 'be-fr': 'Les godets basculants disposent d\'un godet hydrauliquement inclinable.', 'de-de': 'Schwenkschaufeln verfügen über eine hydraulisch schwenkbare Schaufel.'},
        'long_description': 'Kantelbakken zijn graafbakken met een hydraulisch kantelbare bak voor het werken aan taluds, hellingen en moeilijk bereikbare hoeken. De kantelhoek tot 45 graden links en rechts biedt maximale flexibiliteit bij grondwerk. Ideaal voor het afwerken van taluds, het graven langs obstakels en het profileren van hellingen. Robuuste constructie met verstevigde scharnierpunten voor intensief gebruik.',
        'long_description_translations': {'be-nl': 'Kantelbakken zijn graafbakken met een hydraulisch kantelbare bak voor het werken aan taluds, hellingen en moeilijk bereikbare hoeken. De kantelhoek tot 45 graden links en rechts biedt maximale flexibiliteit bij grondwerk. Ideaal voor het afwerken van taluds, het graven langs obstakels en het profileren van hellingen. Robuuste constructie met verstevigde scharnierpunten voor intensief gebruik.', 'nl-nl': 'Kantelbakken zijn graafbakken met een hydraulisch kantelbare bak voor het werken aan taluds, hellingen en moeilijk bereikbare hoeken. De kantelhoek tot 45 graden links en rechts biedt maximale flexibiliteit bij grondwerk. Ideaal voor het afwerken van taluds, het graven langs obstakels en het profileren van hellingen. Robuuste constructie met verstevigde scharnierpunten voor intensief gebruik.', 'be-fr': 'Les godets basculants sont des godets avec un godet hydrauliquement inclinable pour travailler sur des talus et des angles difficiles d\'accès.', 'de-de': 'Schwenkschaufeln sind Schaufeln mit hydraulisch schwenkbarer Schaufel für Böschungen und schwer zugängliche Ecken.'}
    },
    'rioolbakken': {
        'title': 'Rioolbakken', 'parent_category': 'graafbakken',
        'title_translations': {'be-nl': 'Rioolbakken', 'nl-nl': 'Rioolbakken', 'be-fr': 'Godets à égouts', 'de-de': 'Kanalschaufeln'},
        'description': 'Rioolbakken met afgeronde bodem voor het graven van rioolsleuven.',
        'description_translations': {'be-nl': 'Rioolbakken met afgeronde bodem voor het graven van rioolsleuven.', 'nl-nl': 'Rioolbakken met afgeronde bodem voor het graven van rioolsleuven.', 'be-fr': 'Les godets à égouts sont des godets spécialement formés.', 'de-de': 'Kanalschaufeln sind speziell geformte Schaufeln.'},
        'long_description': 'Rioolbakken zijn speciaal gevormde graafbakken met een afgeronde bodem voor het graven van rioolsleuven en kabelgoten. De ronde bodemprofiel creëert een perfecte bedding voor rioolbuizen en kabels zonder nabewerking. Ideaal voor riolering, drainage en nutsvoorzieningen. De smalle constructie minimaliseert grondverzet en zorgt voor efficiënt werken in stedelijke omgevingen.',
        'long_description_translations': {'be-nl': 'Rioolbakken zijn speciaal gevormde graafbakken met een afgeronde bodem voor het graven van rioolsleuven en kabelgoten. De ronde bodemprofiel creëert een perfecte bedding voor rioolbuizen en kabels zonder nabewerking. Ideaal voor riolering, drainage en nutsvoorzieningen. De smalle constructie minimaliseert grondverzet en zorgt voor efficiënt werken in stedelijke omgevingen.', 'nl-nl': 'Rioolbakken zijn speciaal gevormde graafbakken met een afgeronde bodem voor het graven van rioolsleuven en kabelgoten. De ronde bodemprofiel creëert een perfecte bedding voor rioolbuizen en kabels zonder nabewerking. Ideaal voor riolering, drainage en nutsvoorzieningen. De smalle constructie minimaliseert grondverzet en zorgt voor efficiënt werken in stedelijke omgevingen.', 'be-fr': 'Les godets à égouts sont des godets spécialement formés avec un fond arrondi pour creuser des tranchées d\'égout.', 'de-de': 'Kanalschaufeln sind speziell geformte Schaufeln mit abgerundetem Boden für Kanalgräben.'}
    },
    'trapezium-bakken': {
        'title': 'Trapezium Bakken', 'parent_category': 'graafbakken',
        'title_translations': {'be-nl': 'Trapezium Bakken', 'nl-nl': 'Trapezium Bakken', 'be-fr': 'Godets trapézoïdaux', 'de-de': 'Trapezschaufeln'},
        'description': 'Trapezium bakken met trapeziumvormig profiel voor stabiele sleuven met schuine wanden.',
        'description_translations': {'be-nl': 'Trapezium bakken met trapeziumvormig profiel voor stabiele sleuven met schuine wanden.', 'nl-nl': 'Trapezium bakken met trapeziumvormig profiel voor stabiele sleuven met schuine wanden.', 'be-fr': 'Les godets trapézoïdaux ont un profil trapézoïdal.', 'de-de': 'Trapezschaufeln haben ein trapezförmiges Profil.'},
        'long_description': 'Trapezium bakken hebben een trapeziumvormig profiel voor het graven van stabiele sleuven met schuine wanden. De afgeschuinde zijwanden voorkomen instorting en voldoen aan veiligheidsnormen voor graafwerk. Perfect voor waterwerken, drainage en situaties waar sleufstabiliteit essentieel is. De brede bovenkant biedt groot volume, terwijl de smalle bodem precisie garandeert.',
        'long_description_translations': {'be-nl': 'Trapezium bakken hebben een trapeziumvormig profiel voor het graven van stabiele sleuven met schuine wanden. De afgeschuinde zijwanden voorkomen instorting en voldoen aan veiligheidsnormen voor graafwerk. Perfect voor waterwerken, drainage en situaties waar sleufstabiliteit essentieel is. De brede bovenkant biedt groot volume, terwijl de smalle bodem precisie garandeert.', 'nl-nl': 'Trapezium bakken hebben een trapeziumvormig profiel voor het graven van stabiele sleuven met schuine wanden. De afgeschuinde zijwanden voorkomen instorting en voldoen aan veiligheidsnormen voor graafwerk. Perfect voor waterwerken, drainage en situaties waar sleufstabiliteit essentieel is. De brede bovenkant biedt groot volume, terwijl de smalle bodem precisie garandeert.', 'be-fr': 'Les godets trapézoïdaux ont un profil trapézoïdal pour creuser des tranchées stables avec des parois inclinées.', 'de-de': 'Trapezschaufeln haben ein trapezförmiges Profil für stabile Gräben mit schrägen Wänden.'}
    },
    'sorteergrijpers': {
        'title': 'Sorteergrijpers', 'parent_category': 'sloop-sorteergrijpers',
        'title_translations': {'be-nl': 'Sorteergrijpers', 'nl-nl': 'Sorteergrijpers', 'be-fr': 'Pinces de tri', 'de-de': 'Sortiergreifer'},
        'description': 'Sorteergrijpers zijn hydraulische grijpers voor het sorteren van bouw- en sloopafval.',
        'description_translations': {'be-nl': 'Sorteergrijpers zijn hydraulische grijpers voor het sorteren van bouw- en sloopafval.', 'nl-nl': 'Sorteergrijpers zijn hydraulische grijpers voor het sorteren van bouw- en sloopafval.', 'be-fr': 'Les pinces de tri sont des pinces hydrauliques.', 'de-de': 'Sortiergreifer sind hydraulische Greifer.'},
        'long_description': 'Sorteergrijpers zijn veelzijdige hydraulische grijpers voor het efficiënt sorteren van bouw- en sloopafval op recyclingparken en overslaglocaties. Met krachtige grijpkracht en robuuste tanden kunnen ze diverse materialen zoals hout, metaal, puin en kunststof scheiden. De hydraulische opening tot 2 meter biedt groot bereik en volume. Ideaal voor afvalverwerking, recycling en materialenhandling.',
        'long_description_translations': {'be-nl': 'Sorteergrijpers zijn veelzijdige hydraulische grijpers voor het efficiënt sorteren van bouw- en sloopafval op recyclingparken en overslaglocaties. Met krachtige grijpkracht en robuuste tanden kunnen ze diverse materialen zoals hout, metaal, puin en kunststof scheiden. De hydraulische opening tot 2 meter biedt groot bereik en volume. Ideaal voor afvalverwerking, recycling en materialenhandling.', 'nl-nl': 'Sorteergrijpers zijn veelzijdige hydraulische grijpers voor het efficiënt sorteren van bouw- en sloopafval op recyclingparken en overslaglocaties. Met krachtige grijpkracht en robuuste tanden kunnen ze diverse materialen zoals hout, metaal, puin en kunststof scheiden. De hydraulische opening tot 2 meter biedt groot bereik en volume. Ideaal voor afvalverwerking, recycling en materialenhandling.', 'be-fr': 'Les pinces de tri sont des pinces hydrauliques polyvalentes pour trier efficacement les déchets de construction.', 'de-de': 'Sortiergreifer sind vielseitige hydraulische Greifer zum effizienten Sortieren von Bau- und Abbruchabfällen.'}
    },
    'sloopgrijpers': {
        'title': 'Sloopgrijpers', 'parent_category': 'sloop-sorteergrijpers',
        'title_translations': {'be-nl': 'Sloopgrijpers', 'nl-nl': 'Sloopgrijpers', 'be-fr': 'Pinces de démolition', 'de-de': 'Abbruchgreifer'},
        'description': 'Sloopgrijpers zijn extra zware grijpers voor afbraakwerk.',
        'description_translations': {'be-nl': 'Sloopgrijpers zijn extra zware grijpers voor afbraakwerk.', 'nl-nl': 'Sloopgrijpers zijn extra zware grijpers voor afbraakwerk.', 'be-fr': 'Les pinces de démolition sont des pinces extra-lourdes.', 'de-de': 'Abbruchgreifer sind extra schwere Greifer.'},
        'long_description': 'Sloopgrijpers zijn extra zware hydraulische grijpers speciaal ontworpen voor intensief afbraak- en sloopwerk. De versterkte constructie met hardox tanden en verstevigde behuizing kan beton, metselwerk en staalconstructies moeiteloos breken en verplaatsen. Hoge grijpkracht tot 30 ton en robuuste cilinders garanderen betrouwbare prestaties bij zware sloop. Perfect voor gebouwsloop, betonrecycling en industriële afbraak.',
        'long_description_translations': {'be-nl': 'Sloopgrijpers zijn extra zware hydraulische grijpers speciaal ontworpen voor intensief afbraak- en sloopwerk. De versterkte constructie met hardox tanden en verstevigde behuizing kan beton, metselwerk en staalconstructies moeiteloos breken en verplaatsen. Hoge grijpkracht tot 30 ton en robuuste cilinders garanderen betrouwbare prestaties bij zware sloop. Perfect voor gebouwsloop, betonrecycling en industriële afbraak.', 'nl-nl': 'Sloopgrijpers zijn extra zware hydraulische grijpers speciaal ontworpen voor intensief afbraak- en sloopwerk. De versterkte constructie met hardox tanden en verstevigde behuizing kan beton, metselwerk en staalconstructies moeiteloos breken en verplaatsen. Hoge grijpkracht tot 30 ton en robuuste cilinders garanderen betrouwbare prestaties bij zware sloop. Perfect voor gebouwsloop, betonrecycling en industriële afbraak.', 'be-fr': 'Les pinces de démolition sont des pinces hydrauliques extra-lourdes spécialement conçues pour les travaux de démolition intensifs.', 'de-de': 'Abbruchgreifer sind extra schwere hydraulische Greifer speziell für intensive Abbrucharbeiten.'}
    },
    'puingrijpers': {
        'title': 'Puingrijpers', 'parent_category': 'sloop-sorteergrijpers',
        'title_translations': {'be-nl': 'Puingrijpers', 'nl-nl': 'Puingrijpers', 'be-fr': 'Pinces à gravats', 'de-de': 'Schuttgreifer'},
        'description': 'Puingrijpers zijn veelzijdige grijpers voor het laden en sorteren van puin.',
        'description_translations': {'be-nl': 'Puingrijpers zijn veelzijdige grijpers voor het laden en sorteren van puin.', 'nl-nl': 'Puingrijpers zijn veelzijdige grijpers voor het laden en sorteren van puin.', 'be-fr': 'Les pinces à gravats sont des pinces polyvalentes.', 'de-de': 'Schuttgreifer sind vielseitige Greifer.'},
        'long_description': 'Puingrijpers zijn veelzijdige hydraulische grijpers voor het efficiënt laden, verplaatsen en sorteren van puin en bouwafval. De brede bekken met geoptimaliseerde tandverdeling grijpen grote volumes in één keer. Geschikt voor beton-, steen- en mengpuin op bouwplaatsen, sloopwerven en recyclingparken. De robuuste constructie combineert groot volume met precisie voor productief puinwerk.',
        'long_description_translations': {'be-nl': 'Puingrijpers zijn veelzijdige hydraulische grijpers voor het efficiënt laden, verplaatsen en sorteren van puin en bouwafval. De brede bekken met geoptimaliseerde tandverdeling grijpen grote volumes in één keer. Geschikt voor beton-, steen- en mengpuin op bouwplaatsen, sloopwerven en recyclingparken. De robuuste constructie combineert groot volume met precisie voor productief puinwerk.', 'nl-nl': 'Puingrijpers zijn veelzijdige hydraulische grijpers voor het efficiënt laden, verplaatsen en sorteren van puin en bouwafval. De brede bekken met geoptimaliseerde tandverdeling grijpen grote volumes in één keer. Geschikt voor beton-, steen- en mengpuin op bouwplaatsen, sloopwerven en recyclingparken. De robuuste constructie combineert groot volume met precisie voor productief puinwerk.', 'be-fr': 'Les pinces à gravats sont des pinces hydrauliques polyvalentes pour charger et trier efficacement les gravats.', 'de-de': 'Schuttgreifer sind vielseitige hydraulische Greifer zum effizienten Laden und Sortieren von Schutt.'}
    },
    'ripper-tanden': {
        'title': 'Ripper Tanden', 'parent_category': 'overige',
        'title_translations': {'be-nl': 'Ripper Tanden', 'nl-nl': 'Ripper Tanden', 'be-fr': 'Dents de ripper', 'de-de': 'Reißzähne'},
        'description': 'Ripper tanden zijn krachtige breektanden voor verhardingen en rotsachtige bodems.',
        'description_translations': {'be-nl': 'Ripper tanden zijn krachtige breektanden voor verhardingen en rotsachtige bodems.', 'nl-nl': 'Ripper tanden zijn krachtige breektanden voor verhardingen en rotsachtige bodems.', 'be-fr': 'Les dents de ripper sont des dents de rupture puissantes.', 'de-de': 'Reißzähne sind kraftvolle Brechzähne.'},
        'long_description': 'Ripper tanden zijn krachtige breektanden voor het losbreken van verhardingen, rotsachtige bodems en bevroren grond. De gehard stalen punt met verstevigde schacht kan zelfs de zwaarste grondsoorten penetreren. Ideaal voor wegenbreekwerk, fundering-sloop en grondbewerking in moeilijke omstandigheden. Verkrijgbaar in diverse lengtes en profielen voor optimale penetratie en breekwerk.',
        'long_description_translations': {'be-nl': 'Ripper tanden zijn krachtige breektanden voor het losbreken van verhardingen, rotsachtige bodems en bevroren grond. De gehard stalen punt met verstevigde schacht kan zelfs de zwaarste grondsoorten penetreren. Ideaal voor wegenbreekwerk, fundering-sloop en grondbewerking in moeilijke omstandigheden. Verkrijgbaar in diverse lengtes en profielen voor optimale penetratie en breekwerk.', 'nl-nl': 'Ripper tanden zijn krachtige breektanden voor het losbreken van verhardingen, rotsachtige bodems en bevroren grond. De gehard stalen punt met verstevigde schacht kan zelfs de zwaarste grondsoorten penetreren. Ideaal voor wegenbreekwerk, fundering-sloop en grondbewerking in moeilijke omstandigheden. Verkrijgbaar in diverse lengtes en profielen voor optimale penetratie en breekwerk.', 'be-fr': 'Les dents de ripper sont des dents de rupture puissantes pour briser les surfaces durcies et les sols rocheux.', 'de-de': 'Reißzähne sind kraftvolle Brechzähne zum Aufbrechen von Befestigungen und felsigen Böden.'}
    },
    'hydraulische-hamers': {
        'title': 'Hydraulische Hamers', 'parent_category': 'overige',
        'title_translations': {'be-nl': 'Hydraulische Hamers', 'nl-nl': 'Hydraulische Hamers', 'be-fr': 'Marteaux hydrauliques', 'de-de': 'Hydraulikhämmer'},
        'description': 'Hydraulische hamers zijn slagkrachtige breekhamers voor beton en asfalt.',
        'description_translations': {'be-nl': 'Hydraulische hamers zijn slagkrachtige breekhamers voor beton en asfalt.', 'nl-nl': 'Hydraulische hamers zijn slagkrachtige breekhamers voor beton en asfalt.', 'be-fr': 'Les marteaux hydrauliques sont des brise-roches puissants.', 'de-de': 'Hydraulikhämmer sind schlagkräftige Abbruchhämmer.'},
        'long_description': 'Hydraulische hamers zijn slagkrachtige breekhamers voor het efficiënt breken van beton, asfalt, natuursteen en andere harde materialen. Met slagfrequenties tot 1400 slagen per minuut en hoge slagenergie breken ze zelfs gewapend beton moeiteloos. Geschikt voor sloopwerk, wegenbouw, fundering en steengroeven. Verkrijgbaar in diverse gewichtsklassen van 50kg tot 2000kg voor alle graafmachines.',
        'long_description_translations': {'be-nl': 'Hydraulische hamers zijn slagkrachtige breekhamers voor het efficiënt breken van beton, asfalt, natuursteen en andere harde materialen. Met slagfrequenties tot 1400 slagen per minuut en hoge slagenergie breken ze zelfs gewapend beton moeiteloos. Geschikt voor sloopwerk, wegenbouw, fundering en steengroeven. Verkrijgbaar in diverse gewichtsklassen van 50kg tot 2000kg voor alle graafmachines.', 'nl-nl': 'Hydraulische hamers zijn slagkrachtige breekhamers voor het efficiënt breken van beton, asfalt, natuursteen en andere harde materialen. Met slagfrequenties tot 1400 slagen per minuut en hoge slagenergie breken ze zelfs gewapend beton moeiteloos. Geschikt voor sloopwerk, wegenbouw, fundering en steengroeven. Verkrijgbaar in diverse gewichtsklassen van 50kg tot 2000kg voor alle graafmachines.', 'be-fr': 'Les marteaux hydrauliques sont des brise-roches puissants pour briser efficacement le béton et l\'asphalte.', 'de-de': 'Hydraulikhämmer sind schlagkräftige Abbruchhämmer zum effizienten Brechen von Beton und Asphalt.'}
    },
    'egaliseerbalken': {
        'title': 'Egaliseerbalken', 'parent_category': 'overige',
        'title_translations': {'be-nl': 'Egaliseerbalken', 'nl-nl': 'Egaliseerbalken', 'be-fr': 'Poutres de nivellement', 'de-de': 'Planierbalken'},
        'description': 'Egaliseerbalken zijn precisie-afwerkingsgereedschap voor het egaliseren van terreinen.',
        'description_translations': {'be-nl': 'Egaliseerbalken zijn precisie-afwerkingsgereedschap voor het egaliseren van terreinen.', 'nl-nl': 'Egaliseerbalken zijn precisie-afwerkingsgereedschap voor het egaliseren van terreinen.', 'be-fr': 'Les poutres de nivellement sont des outils de finition de précision.', 'de-de': 'Planierbalken sind Präzisions-Endbearbeitungswerkzeuge.'},
        'long_description': 'Egaliseerbalken zijn precisie-afwerkingsgereedschap voor het egaliseren en nivelleren van terreinen, parkings en sportvelden. De verstelbare balk met laser-geleiding creëert perfecte vlakke oppervlakken met millimeterprecisie. Ideaal voor terreinafwerking, parkeerplaatsen, sportvelden en landschapsarchitectuur. Hydraulisch verstelbaar voor optimale controle en efficiëntie bij grondafwerking.',
        'long_description_translations': {'be-nl': 'Egaliseerbalken zijn precisie-afwerkingsgereedschap voor het egaliseren en nivelleren van terreinen, parkings en sportvelden. De verstelbare balk met laser-geleiding creëert perfecte vlakke oppervlakken met millimeterprecisie. Ideaal voor terreinafwerking, parkeerplaatsen, sportvelden en landschapsarchitectuur. Hydraulisch verstelbaar voor optimale controle en efficiëntie bij grondafwerking.', 'nl-nl': 'Egaliseerbalken zijn precisie-afwerkingsgereedschap voor het egaliseren en nivelleren van terreinen, parkings en sportvelden. De verstelbare balk met laser-geleiding creëert perfecte vlakke oppervlakken met millimeterprecisie. Ideaal voor terreinafwerking, parkeerplaatsen, sportvelden en landschapsarchitectuur. Hydraulisch verstelbaar voor optimale controle en efficiëntie bij grondafwerking.', 'be-fr': 'Les poutres de nivellement sont des outils de finition de précision pour niveler les terrains.', 'de-de': 'Planierbalken sind Präzisions-Endbearbeitungswerkzeuge zum Nivellieren von Gelände.'}
    },
    'verdichtingsplaten': {
        'title': 'Verdichtingsplaten', 'parent_category': 'overige',
        'title_translations': {'be-nl': 'Verdichtingsplaten', 'nl-nl': 'Verdichtingsplaten', 'be-fr': 'Plaques de compactage', 'de-de': 'Verdichtungsplatten'},
        'description': 'Hydraulische verdichtingsplaten voor het verdichten van grond, zand en grind.',
        'description_translations': {'be-nl': 'Hydraulische verdichtingsplaten voor het verdichten van grond, zand en grind.', 'nl-nl': 'Hydraulische verdichtingsplaten voor het verdichten van grond, zand en grind.', 'be-fr': 'Plaques de compactage hydrauliques pour le compactage du sol.', 'de-de': 'Hydraulische Verdichtungsplatten zum Verdichten von Erde.'},
        'long_description': 'Hydraulische verdichtingsplaten zijn trilplaten voor het effectief verdichten van grond, zand, grind en asfalt in sleuven en moeilijk bereikbare plaatsen. De hoogfrequente trillingen tot 4000 trillingen per minuut zorgen voor optimale verdichting. Perfect voor leidingsleuven, fundering, wegenbouw en terreinverharding. Verkrijgbaar in diverse formaten en gewichten voor alle graafmachineklassen.',
        'long_description_translations': {'be-nl': 'Hydraulische verdichtingsplaten zijn trilplaten voor het effectief verdichten van grond, zand, grind en asfalt in sleuven en moeilijk bereikbare plaatsen. De hoogfrequente trillingen tot 4000 trillingen per minuut zorgen voor optimale verdichting. Perfect voor leidingsleuven, fundering, wegenbouw en terreinverharding. Verkrijgbaar in diverse formaten en gewichten voor alle graafmachineklassen.', 'nl-nl': 'Hydraulische verdichtingsplaten zijn trilplaten voor het effectief verdichten van grond, zand, grind en asfalt in sleuven en moeilijk bereikbare plaatsen. De hoogfrequente trillingen tot 4000 trillingen per minuut zorgen voor optimale verdichting. Perfect voor leidingsleuven, fundering, wegenbouw en terreinverharding. Verkrijgbaar in diverse formaten en gewichten voor alle graafmachineklassen.', 'be-fr': 'Les plaques de compactage hydrauliques sont des plaques vibrantes pour compacter efficacement le sol.', 'de-de': 'Hydraulische Verdichtungsplatten sind Rüttelplatten zum effektiven Verdichten von Erde.'}
    }
}

LABELS = {
    'be-nl': {'home': 'Home', 'products': 'Producten', 'subcategories': 'Subcategorieën', 'products_found': 'producten gevonden', 'filters': 'Filters', 'clear': 'Wissen', 'brand': 'Merk', 'loading_brands': 'Merken laden...', 'volume': 'Inhoud (liter)', 'excavator_class': 'Graafmachine Klasse', 'width': 'Breedte (mm)', 'attachment': 'Ophanging', 'apply_filters': 'Filters Toepassen', 'sort': 'Sorteren:', 'newest': 'Nieuwste eerst', 'oldest': 'Oudste eerst', 'name_az': 'Naam A-Z', 'name_za': 'Naam Z-A', 'loading': 'Producten laden...', 'prev': 'Vorige', 'next': 'Volgende', 'meta_suffix': '| Structon'},
    'nl-nl': {'home': 'Home', 'products': 'Producten', 'subcategories': 'Subcategorieën', 'products_found': 'producten gevonden', 'filters': 'Filters', 'clear': 'Wissen', 'brand': 'Merk', 'loading_brands': 'Merken laden...', 'volume': 'Inhoud (liter)', 'excavator_class': 'Graafmachine Klasse', 'width': 'Breedte (mm)', 'attachment': 'Ophanging', 'apply_filters': 'Filters Toepassen', 'sort': 'Sorteren:', 'newest': 'Nieuwste eerst', 'oldest': 'Oudste eerst', 'name_az': 'Naam A-Z', 'name_za': 'Naam Z-A', 'loading': 'Producten laden...', 'prev': 'Vorige', 'next': 'Volgende', 'meta_suffix': '| Structon'},
    'be-fr': {'home': 'Accueil', 'products': 'Produits', 'subcategories': 'Sous-catégories', 'products_found': 'produits trouvés', 'filters': 'Filtres', 'clear': 'Effacer', 'brand': 'Marque', 'loading_brands': 'Chargement...', 'volume': 'Contenu (litres)', 'excavator_class': 'Classe d\'excavatrice', 'width': 'Largeur (mm)', 'attachment': 'Fixation', 'apply_filters': 'Appliquer', 'sort': 'Trier:', 'newest': 'Plus récent', 'oldest': 'Plus ancien', 'name_az': 'Nom A-Z', 'name_za': 'Nom Z-A', 'loading': 'Chargement...', 'prev': 'Précédent', 'next': 'Suivant', 'meta_suffix': '| Structon'},
    'de-de': {'home': 'Startseite', 'products': 'Produkte', 'subcategories': 'Unterkategorien', 'products_found': 'Produkte gefunden', 'filters': 'Filter', 'clear': 'Löschen', 'brand': 'Marke', 'loading_brands': 'Laden...', 'volume': 'Inhalt (Liter)', 'excavator_class': 'Baggerklasse', 'width': 'Breite (mm)', 'attachment': 'Aufhängung', 'apply_filters': 'Anwenden', 'sort': 'Sortieren:', 'newest': 'Neueste', 'oldest': 'Älteste', 'name_az': 'Name A-Z', 'name_za': 'Name Z-A', 'loading': 'Laden...', 'prev': 'Zurück', 'next': 'Weiter', 'meta_suffix': '| Structon'}
}
